### ISSUE TITLE
openapi message_type is defined as an enum instead of a const

### ISSUE THREAD

**Issue by lfse-slafleur** [flexiblepower/s2-ws-json#17]
The field `message_type` is currently defined as an enum in `openapi.yml`.

Example from line 807:
```yaml
      properties:
        message_type:
          type: string
          enum: [ "DDBC.TimerStatus" ]
```

Rather a constant is expected such as:
```yaml
        message_type:
          const: DDBC.TimerStatus
          type: string
```

A `const` is generated differently by generators such as datamodel-codegen. An `enum` will be generated to its own type and it is harder to use while a `const` will remain a simple string.
